apiVersion: gateway.networking.k8s.io/v1beta1
kind: Gateway
metadata:
  name: control-gateway
  namespace: travel-control
spec:
  gatewayClassName: istio
  listeners:
  - name: http
    port: 80
    protocol: HTTP
---
apiVersion: gateway.networking.k8s.io/v1beta1
kind: HTTPRoute
metadata:
  name: control
  namespace: travel-control
spec:
  parentRefs:
  - name: travel-control-gateway
---
apiVersion: gateway.networking.k8s.io/v1beta1
kind: Gateway
metadata:
  name: portal-gateway
  namespace: travel-portal
spec:
  gatewayClassName: istio
  listeners:
  - name: http
    port: 8000
    protocol: HTTP
---
apiVersion: gateway.networking.k8s.io/v1beta1
kind: HTTPRoute
metadata:
  name: portal
  namespace: travel-portal
spec:
  parentRefs:
  - name: travel-portal-gateway
